# @Author: nickchen
# @Date:   2020-08-07T08:27:03+08:00
# @Last modified by:   nickchen
# @Last modified time: 2020-08-07T14:07:39+08:00
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-hello
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: service-hello
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: service-hello
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: service-hello
        image: {{ .Values.global.image.registry }}/service-hello:{{ .Values.global.image.tag }}
        #image: {{ .Values.global.image.namespace }}:{{ .Values.global.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.servicehelloPort }}
            name: service-hello
      dnsPolicy: ClusterFirst
      {{ if .Values.global.image.pullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullsecrets }}
      {{ end }}
      restartPolicy: Always
