# @Author: nickchen
# @Date:   2020-08-07T08:27:51+08:00
# @Last modified by:   nickchen
# @Last modified time: 2020-08-07T14:18:41+08:00
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-hello
    release: {{ .Release.Name }}
  name: service-hello
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: service-hello
    port: {{ .Values.servicehelloPort }}
    targetPort: service-hello
  type: ClusterIP
  selector:
    app: service-hello
    release: {{ .Release.Name }}
