# @Author: nickchen
# @Date:   2020-08-07T08:27:03+08:00
# @Last modified by:   nickchen
# @Last modified time: 2020-08-07T09:21:56+08:00
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcx
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: xcx
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: xcx
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: xcx
        image: {{ .Values.global.image.registry }}/xcx:{{ .Values.global.image.tag }}
        #image: {{ .Values.global.image.namespace }}:{{ .Values.global.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.xcxPort }}
            name: xcx
      dnsPolicy: ClusterFirst
      {{ if .Values.global.image.pullsecrets }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullsecrets }}
      {{ end }}
      restartPolicy: Always
