# @Author: nickchen
# @Date:   2020-08-07T08:28:13+08:00
# @Last modified by:   nickchen
# @Last modified time: 2020-08-07T13:56:54+08:00
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eurekaserver
    release: {{ .Release.Name }}
  name: eurekaserver-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: eurekaserver
    port: {{ .Values.eurekaserverPort }}
    targetPort: eurekaserver
    nodePort:
  type: NodePort
  selector:
    app: eurekaserver
    release: "{{ .Release.Name }}"
